### ISSUE TITLE
Sample covariance calculation

### ISSUE THREAD

**Issue by al-bert** [earowang/hts#62]
Thank you for this package! I'd like to confirm the sample covariance calculation in the "MinT" function here: https://github.com/earowang/hts/blob/master/R/MinT.R#L184
```r
n <- nrow(res)
w.1 <- crossprod(res) / n
```

I expected `w.1` to be the usual sample covariance matrix instead:
```r
w.1 <- cov(allr)

# same as
n <- nrow(res)
res.centered <- scale(res, center=TRUE, scale=FALSE)
crossprod(res.centered)/(n-1)
```

The difference is that the usual sample covariance matrix (1) centers the residuals and (2) divides by n-1 instead of n for an unbiased estimate.
1. Do you not center residuals because you assume base forecasts are unbiased? This seems to be the intent from eqn3 and the formula given in lemma 1. https://robjhyndman.com/papers/mint.pdf
2. Is the the choice to normalize by `n` instead of `n-1` also intentional?

Thank you for confirming!

**Comment by robjhyndman** [comment]
1. Yes, it is assumed that the base forecasts are unbiased. Hence the best covariance estimate does not remove the mean of the residuals.
2. Because we don't remove the mean, there is no need to subtract one from the sample size. The n-1 divisor is to adjust for the degrees of freedom used when subtracting the mean.

**Comment by al-bert** [comment]
Makes sense, thanks for the explanation!
